### ISSUE TITLE
I think the "poke me" link is broken in latest post

### ISSUE THREAD

**Issue by maxjacobson** [nickcherry/cherry-pickings#1]

**Comment by nickcherry** [comment]
Who needs a continuous integration server when you have @maxjacobson , amirite?

**Comment by nickcherry** [comment]
Fixed https://github.com/nickcherry/cherry-pickings/commit/030acc7fcea07763fd1efe50eff420e8ba8c6abe

**Comment by nickcherry** [comment]
I lied. Fixed https://github.com/nickcherry/cherry-pickings/commit/61c407956e489fc047de3e8eb3c9f47120f4404f

**Comment by nickcherry** [comment]
Not kidding this time https://github.com/nickcherry/cherry-pickings/commit/53ea71b0675ef034cf05d5c75013d7ecadf7342d

**Comment by maxjacobson** [comment]
haha 3 strikes... you're in!
